---
# vim: filetype=ansible.yaml
# NON-SINGLETON cluster - 2nd and after HA control plane nodes.

# The singleton is any already running k3s controlplane node.  Mostly we
# just need to have the correct node token to use on any other control
# plane node, because we initialize everything on the first one and then
# all other control plane nodes will join on the running node for the
# initial setup.
#
# Otherwise they won't be able to communicate and you'd have three
# isolated control planes, not a single HA control plane.

- name: Copy Jinja template
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: '0600'

- name: Copy K3s service file
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: '0644'

- name: Enable and check K3s service
  any_errors_fatal: true
  throttle: 1
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true

- name: Get list of certs
  ansible.builtin.find:
    paths: /var/lib/rancher/k3s/server/tls
    patterns: "*.crt"
  register: controlplane_k3s_certs

- name: Chmod 0600 /var/lib/rancher/k3s/server/tls/*.crt
  ansible.builtin.file:
    path: "{{ controlplane_k3s_cert.path }}"
    mode: '0600'
  with_items: "{{ controlplane_k3s_certs.files }}"
  loop_control:
    loop_var: controlplane_k3s_cert
